"""metalworks.contract — the stable public data contract.

Pydantic models are the single source of truth for every surface (library,
CLI, MCP tools, generated TypeScript). These models are the STABLE part of
the 0.x API; everything outside `metalworks.contract` may change in any 0.x
release.

JSON-schema snapshots live in `contract/schema/` and are diff-gated in CI;
TypeScript twins are generated by `scripts/gen_ts_types.py`.
"""

from metalworks.contract.evidence import (
    EvidenceRecord,
    EvidenceRef,
)
from metalworks.contract.reddit import (
    ComplianceVerdict,
    DiscoveryContext,
    InboxItem,
    LintViolation,
    Opportunity,
    Persona,
    PersonaSet,
    PostLintVerdict,
    RedditComment,
    RedditPost,
    SubredditIntel,
)
from metalworks.contract.research import (
    AudienceAttribute,
    AudienceProfile,
    AudienceSegment,
    CorpusStats,
    CrossReference,
    DemandReport,
    ExplorationReport,
    Fork,
    InsightCluster,
    MarketSizing,
    PriceEvidence,
    PriceFinding,
    QuoteCitation,
    ReportSummary,
    ResearchBrief,
    RunSummary,
    SignalStrength,
    SlotPlan,
    SourceMapEntry,
    TargetSubreddit,
    TriageThresholds,
    WebFinding,
)

__all__ = [
    "AudienceAttribute",
    "AudienceProfile",
    "AudienceSegment",
    "ComplianceVerdict",
    "CorpusStats",
    "CrossReference",
    "DemandReport",
    "DiscoveryContext",
    "EvidenceRecord",
    "EvidenceRef",
    "ExplorationReport",
    "Fork",
    "InboxItem",
    "InsightCluster",
    "LintViolation",
    "MarketSizing",
    "Opportunity",
    "Persona",
    "PersonaSet",
    "PostLintVerdict",
    "PriceEvidence",
    "PriceFinding",
    "QuoteCitation",
    "RedditComment",
    "RedditPost",
    "ReportSummary",
    "ResearchBrief",
    "RunSummary",
    "SignalStrength",
    "SlotPlan",
    "SourceMapEntry",
    "SubredditIntel",
    "TargetSubreddit",
    "TriageThresholds",
    "WebFinding",
]
