"""metalworks.contract — the stable public data contract.

Pydantic models are the single source of truth for every surface (library,
CLI, MCP tools, generated TypeScript). These models are the STABLE part of
the 0.x API; everything outside `metalworks.contract` may change in any 0.x
release.

JSON-schema snapshots live in `contract/schema/` and are diff-gated in CI;
TypeScript twins are generated by `scripts/gen_ts_types.py`.
"""

from metalworks.contract.bundle import Research
from metalworks.contract.evidence import (
    EvidenceRecord,
    EvidenceRef,
)
from metalworks.contract.landscape import (
    Competitor,
    CompetitorMap,
    GapClaim,
    StrengthClaim,
)
from metalworks.contract.launch import (
    ChannelPlan,
    ChannelStep,
    ClaimCitation,
    LaunchAsset,
)
from metalworks.contract.marketing import (
    CitationStrategy,
    ContentPage,
    ContentPlan,
    FaqItem,
)
from metalworks.contract.positioning import (
    PositioningBrief,
    PriceHypothesis,
    WedgeClaim,
)
from metalworks.contract.reddit import (
    ComplianceVerdict,
    DiscoveryContext,
    InboxItem,
    LintViolation,
    Opportunity,
    Persona,
    PersonaSet,
    PostLintVerdict,
    RedditComment,
    RedditPost,
    SubredditIntel,
)
from metalworks.contract.research import (
    AudienceAttribute,
    AudienceProfile,
    AudienceSegment,
    CorpusStats,
    CrossReference,
    DemandReport,
    ExplorationReport,
    Fork,
    InsightCluster,
    MarketSizing,
    PriceEvidence,
    PriceFinding,
    QuoteCitation,
    ReportSummary,
    ResearchBrief,
    RunSummary,
    SignalStrength,
    SlotPlan,
    SourceMapEntry,
    TargetSubreddit,
    TriageThresholds,
    WebFinding,
)
from metalworks.contract.site import (
    MarketingSite,
    SiteSection,
)
from metalworks.contract.surface import (
    DesignBrief,
    RubricDimension,
    Screen,
    SurfaceRecommendation,
    TradeOff,
    UxSkeleton,
)

__all__ = [  # noqa: RUF022 — grouped by domain (evidence / research / reddit), not globally sorted
    # Evidence chain — the cross-stage spine every pillar resolves against.
    "EvidenceRecord",
    "EvidenceRef",
    # Research stage — demand report, its parts, and the `Research` bundle.
    "AudienceAttribute",
    "AudienceProfile",
    "AudienceSegment",
    "CorpusStats",
    "CrossReference",
    "DemandReport",
    "ExplorationReport",
    "Fork",
    "InsightCluster",
    "MarketSizing",
    "PriceEvidence",
    "PriceFinding",
    "QuoteCitation",
    "ReportSummary",
    "Research",
    "ResearchBrief",
    "RunSummary",
    "SignalStrength",
    "SlotPlan",
    "SourceMapEntry",
    "TargetSubreddit",
    "TriageThresholds",
    "WebFinding",
    # Landscape stage (Pillar A) — the grounded competitive map.
    "Competitor",
    "CompetitorMap",
    "GapClaim",
    "StrengthClaim",
    # Positioning stage (Pillar B) — the grounded Dunford wedge + price hypothesis.
    "PositioningBrief",
    "PriceHypothesis",
    "WedgeClaim",
    # Design stage (Pillar C) — the grounded surface decision + UX skeleton.
    "DesignBrief",
    "RubricDimension",
    "Screen",
    "SurfaceRecommendation",
    "TradeOff",
    "UxSkeleton",
    # Site stage (Pillar E) — the grounded marketing site + its sections.
    "MarketingSite",
    "SiteSection",
    # Launch stage (Pillar F) — channel-native cited assets + human-executed plan.
    "ChannelPlan",
    "ChannelStep",
    "ClaimCitation",
    "LaunchAsset",
    # Content/SEO stage (Pillar G) — the deterministic content plan + citation strategy.
    "CitationStrategy",
    "ContentPage",
    "ContentPlan",
    "FaqItem",
    # Reddit + discovery — engagement surfaces and the compliance gate.
    "ComplianceVerdict",
    "DiscoveryContext",
    "InboxItem",
    "LintViolation",
    "Opportunity",
    "Persona",
    "PersonaSet",
    "PostLintVerdict",
    "RedditComment",
    "RedditPost",
    "SubredditIntel",
]
