"""Research data contract — single source of truth.

Field names are stable so downstream consumers can depend on them directly.

Every surface imports its shape from here:

    research pipeline ──┐
    CLI / REST          ├─► DemandReport (this module)
    MCP tools ──────────┘

TypeScript twins are generated by scripts/gen_ts_types.py — never
hand-maintained. JSON-schema snapshots in contract/schema/ are diff-gated.

Structural-provenance contract:
- The LLM proposes clusters + candidate quotes + web findings + cross-
  references; the service verifies quotes (exact-match), validates indices
  (list-id-prefixed at the LLM boundary, see metalworks.research.triangulate),
  and assembles THIS.
- Quote text is exact-matched to a stored source comment — no fabrication.
  Citations are the source-neutral `ResolvedCitation` (materialized inline so a
  report stays self-contained over git + MCP); `CitationRef` is the thin
  live-view pointer used where the corpus is present.
- Web findings carry URL + title + published_at from the grounding tool's
  citation metadata, not from the LLM's prose.
- Cross-references are indices-to-indices, never free text.
- Counts (threads_relevant, mention_count, distinct_author_count,
  must_address_resolution) are deterministic from membership.

Brief immutability: briefs are UUID-per-version. Editing a brief creates a
new row with a fresh brief_id and a `supersedes` pointer to the prior
version. Runs FK to a single brief_id; a re-run after edit creates a new run
pointing at the new brief.

Multi-tenancy: `workspace_id` / `client_id` are preserved for hosted
deployments but default to "local" — a library user never has to think
about tenants.
"""

from __future__ import annotations

import hashlib
import math
from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, computed_field

from metalworks.contract.evidence import EvidenceRecord

# ──────────────────────────────────────────────────────────────────────────
# Evidence ids
# ──────────────────────────────────────────────────────────────────────────


def _evidence_id(prefix: str, *parts: str) -> str:
    """Deterministic, content-addressed evidence id, e.g. ``q:1a2b3c4d5e6f``.

    Stable across (de)serialization because it is a pure function of the
    evidence content. Scoped by resolution-within-report (see
    ``metalworks.contract.evidence``): unique + stable within one report is
    enough, so we do not embed ``report_id``. The ``\\x1f`` unit separator
    keeps ``("ab", "c")`` distinct from ``("a", "bc")``.
    """
    digest = hashlib.sha1("\x1f".join(parts).encode("utf-8")).hexdigest()[:12]
    return f"{prefix}:{digest}"


# ──────────────────────────────────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────────────────────────────────


class Fork(StrEnum):
    """Which axis is held fixed while the other is optimized.

    Carried forward for backwards compatibility with migrated reports.
    New-shape briefs use the slot_plan field directly.
    """

    PRODUCT_PINNED = "product_pinned"
    DEMOGRAPHIC_PINNED = "demographic_pinned"
    BOTH = "both"


class SignalStrength(StrEnum):
    """Per-cluster confidence, driven by distinct-author count.

    Rendered as a text-labelled chip (never color alone) so a thin-evidence
    cluster never reads as authoritative as a well-supported one.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ──────────────────────────────────────────────────────────────────────────
# Provenance primitives
# ──────────────────────────────────────────────────────────────────────────


class CitationRef(BaseModel):
    """The thin, live-view citation form: a pointer into the loaded corpus.

    Used INTERNALLY during synthesis (and a future refresh path) where the
    corpus is present, so a citation can resolve verbatim text/url on demand
    instead of carrying them inline. Never the persisted/serialized shape — a
    `DemandReport` that leaves the process (committed to git, sent over MCP)
    always carries the materialized `ResolvedCitation` instead, because a
    detached report has no corpus to resolve against.
    """

    evidence_id: str = Field(
        description="Content-addressed citation id (``q:<hash>``); matches the resolved form's id."
    )
    record_id: str = Field(
        description="Corpus-wide id of the backing record/comment (resolve against the corpus)."
    )
    kind: Literal["quote"] = Field(
        default="quote", description="Evidence family — quote for a cluster citation."
    )


class ResolvedCitation(BaseModel):
    """One verified, source-neutral quote backing a cluster — the PORTABLE form.

    This is what serializes to ``runs/*.json``, ``research.md``, and every MCP
    response. It carries the verbatim ``text`` + ``source_url`` INLINE so a
    report stays readable when detached from the corpus (committed to git, sent
    over the wire) — the portability guarantee.

    `text` MUST exact-match the backing source comment (the quote-verification
    gate) — the service rejects any quote that doesn't, so a ResolvedCitation
    that reaches this contract is guaranteed real.

    Generic over sources: it replaces the Reddit-shaped fields of the old
    ``QuoteCitation`` (``permalink`` → ``source_url``, ``subreddit`` → ``source``
    (+ ``source_name`` / ``extra``), ``upvotes`` → ``engagement``).
    """

    evidence_id: str = Field(
        default="",
        description="Stable content-addressed citation id (``q:<hash of source_url|text>``). "
        "Defaulted/recomputed by the `id` computed field; carried so a CitationRef matches.",
    )
    record_id: str = Field(
        default="",
        description="Corpus-wide id of the backing record/comment, for live re-resolution.",
    )
    source: str = Field(
        default="reddit",
        description="Origin source, e.g. 'reddit', 'hackernews', 'reviews'.",
    )
    source_name: str = Field(
        default="",
        description="Human-readable origin label, e.g. 'r/Supplements' for Reddit.",
    )
    source_url: str = Field(
        default="", description="Resolvable link to the quote in context (the provenance link)."
    )
    text: str = Field(description="Verbatim quote, exact-matched to the source comment.")
    author_hash: str = Field(
        description="Stable pseudonymous author id (salted hash) — for distinct-author "
        "counting, never the raw username. Pseudonymization, not anonymization."
    )
    engagement: int = Field(
        default=0,
        description="Source-native engagement signal (Reddit upvotes, HN points, …), for context.",
    )
    extra: dict[str, Any] = Field(
        default_factory=dict,
        description="Source-specific fields that don't earn a spine column.",
    )

    @computed_field
    @property
    def id(self) -> str:
        """Stable content-addressed evidence id (``q:<hash of source_url|text>``)."""
        return _evidence_id("q", self.source_url, self.text)

    def as_ref(self) -> CitationRef:
        """The thin live-view pointer for this resolved citation."""
        return CitationRef(evidence_id=self.id, record_id=self.record_id, kind="quote")


class InsightCluster(BaseModel):
    """One ranked consumer-insight theme with its evidence."""

    rank: int = Field(description="1-based rank within the report (by demand_score).")
    claim: str = Field(
        description="One-line synthesized insight (what consumers want/feel/struggle with)."
    )
    demand_score: float = Field(
        description="Ranking signal. Weights distinct-author breadth ABOVE single-post virality "
        "(50 authors x 2 upvotes outranks 1 author x 200 upvotes)."
    )
    distinct_author_count: int = Field(
        description="Number of DISTINCT authors expressing this — the honest base rate, "
        "not mention count."
    )
    mention_count: int = Field(
        description="Total mentions (>= distinct_author_count). Kept separate so base-rate "
        "honesty is visible."
    )
    signal: SignalStrength = Field(
        description="Confidence chip, derived from distinct_author_count."
    )
    quotes: list[ResolvedCitation] = Field(
        description="2-3 verified quotes (materialized, portable). A cluster with zero verified "
        "quotes is never shipped (no-quote-no-theme)."
    )
    attribution_method: str | None = Field(default=None)
    attribution_confidence: str | None = Field(default=None)
    demographic_match: float | None = Field(default=None)


# ──────────────────────────────────────────────────────────────────────────
# Audience / market / pricing
# ──────────────────────────────────────────────────────────────────────────


class SlotPlan(BaseModel):
    product: str | None = Field(default=None)
    audience: str | None = Field(default=None)
    price: float | None = Field(default=None)
    given: list[str] = Field(default_factory=list)
    find: list[str] = Field(default_factory=list)

    @classmethod
    def resolve(
        cls,
        *,
        product: str | None = None,
        audience: str | None = None,
        price: float | None = None,
    ) -> SlotPlan:
        vals: dict[str, object] = {"product": product, "audience": audience, "price": price}

        def is_given(name: str, v: object) -> bool:
            if name == "price":
                return isinstance(v, int | float) and not isinstance(v, bool) and math.isfinite(v)
            return isinstance(v, str) and v.strip() != ""

        given = [n for n, v in vals.items() if is_given(n, v)]
        if not given:
            raise ValueError(
                "At least one slot (product, audience, or price) must be given as the seed."
            )
        find = [n for n in ("product", "audience", "price") if n not in given]
        return cls(product=product, audience=audience, price=price, given=given, find=find)


class AudienceAttribute(BaseModel):
    estimate: str
    confidence: SignalStrength
    evidence: str


class AudienceProfile(BaseModel):
    age_range: AudienceAttribute | None = None
    income_band: AudienceAttribute | None = None
    geography: AudienceAttribute | None = None
    buying_behavior: AudienceAttribute | None = None
    caveat: str | None = None


class AudienceSegment(BaseModel):
    name: str
    profile: AudienceProfile
    preferences: list[str] = Field(default_factory=list)
    demand_score: float
    distinct_author_count: int


class PriceEvidence(BaseModel):
    text: str
    kind: str
    amount: float | None = None
    permalink: str | None = None

    @computed_field
    @property
    def id(self) -> str:
        """Stable content-addressed evidence id (``p:<hash of permalink|text>``)."""
        return _evidence_id("p", self.permalink or "", self.text)


class PriceFinding(BaseModel):
    low: float | None = None
    high: float | None = None
    currency: str = "USD"
    confidence: SignalStrength | None = None
    evidence: list[PriceEvidence] = Field(default_factory=list[PriceEvidence])
    insufficient_signal: bool = False


class SourceMapEntry(BaseModel):
    source: str = Field(
        default="",
        description="Source-neutral origin label for this map row (e.g. 'r/Supplements').",
    )
    subreddit: str = Field(
        default="",
        description="Deprecated Reddit alias for `source`; kept additive so the pipeline's "
        "existing population still validates. Read `source`.",
    )
    subscribers: int | None = None
    threads_examined: int = 0
    skew: str | None = None


class MarketSizing(BaseModel):
    reddit_floor: int
    addressable_market: int
    penetration: dict[str, float]


# ──────────────────────────────────────────────────────────────────────────
# Research Brief
# ──────────────────────────────────────────────────────────────────────────


class TargetSubreddit(BaseModel):
    """A subreddit the planner suggested for this brief, with its rationale.

    The rationale is what the planner showed the user during D5 ("Target
    subreddits"). It's persisted so the report can cite back to the
    planner's reasoning when the user reads the source_map.
    """

    name: str = Field(description="Subreddit name without 'r/' prefix.")
    rationale: str = Field(description="One-line reason this sub was suggested.")


class TriageThresholds(BaseModel):
    """Three-bucket cutoffs for the exploration step.

    Top auto_accept_pct: high cosine to question → skip LLM, accept.
    Bottom auto_reject_pct: low cosine → skip LLM, reject.
    Middle: LLM classifier with confidence.

    Gate on absolute cosine bands AND percentile. Both cosine_floor /
    cosine_ceiling and the percentages are honored; if they disagree by >5%
    relevance rate, the triage step alerts.
    """

    auto_accept_pct: float = Field(default=0.20, ge=0.0, le=1.0)
    auto_reject_pct: float = Field(default=0.50, ge=0.0, le=1.0)
    cosine_floor: float | None = Field(
        default=None,
        description="Absolute cosine below which to auto-reject regardless of percentile. "
        "None = percentile-only.",
    )
    cosine_ceiling: float | None = Field(
        default=None,
        description="Absolute cosine above which to auto-accept regardless of percentile. "
        "None = percentile-only.",
    )


class ResearchBrief(BaseModel):
    """The contract produced by the conversational planner.

    A Brief is the persisted, versioned record of what the planner and the
    user agreed to research. Briefs are IMMUTABLE: editing a brief writes a
    new row with a fresh `brief_id` and a `supersedes` pointer to the prior
    version. Runs FK to a single brief_id; a re-run after edit creates a new
    run pointing at the new brief.
    """

    brief_id: str = Field(description="Stable UUID for this version of the brief.")
    workspace_id: str = Field(
        default="local",
        description="Owning tenant. Defaults to 'local' for library/CLI use.",
    )
    version: int = Field(
        default=1, description="Monotonic version counter within the supersedes chain."
    )
    supersedes: str | None = Field(
        default=None,
        description="Prior brief_id this version replaces. None for the first version.",
    )

    # Refined intent (planner D1-D4)
    question: str = Field(
        description="The refined research question after the planner conversation."
    )
    decision_context: str = Field(description="What decision will this research inform.")
    success_criteria: list[str] = Field(
        description="How the user will judge if the report did its job."
    )
    must_address: list[str] = Field(
        description="Specific sub-questions the report MUST answer. Surfaced in "
        "must_address_resolution."
    )

    # Sources (planner D5-D7)
    target_subreddits: list[TargetSubreddit] = Field(
        description="Reddit communities the corpus pull will cover."
    )
    web_research_directions: list[str] = Field(
        description="External angles to pursue in the web stream."
    )
    excluded_sources: list[str] = Field(
        default_factory=list, description="Explicitly out of scope."
    )

    # Scope (planner D6)
    time_window_months: int = Field(
        default=12, description="How far back to pull from the historical corpus."
    )
    relevance_rubric: str = Field(
        description="One-paragraph definition of relevance the exploration classifier follows. "
        "Goes in the user role of the classifier prompt, never system."
    )
    triage_thresholds: TriageThresholds = Field(default_factory=TriageThresholds)

    # Output (planner D8)
    output_template: Literal["full", "brief_only"] = Field(default="full")
    confidence_threshold: SignalStrength = Field(default=SignalStrength.MEDIUM)

    # Lifecycle
    finalized_at: datetime | None = Field(
        default=None,
        description="When the user confirmed the brief preview and kicked off the run.",
    )


# ──────────────────────────────────────────────────────────────────────────
# Web findings (the web stream's structured output)
# ──────────────────────────────────────────────────────────────────────────


class WebFinding(BaseModel):
    """One structured finding from the web research stream.

    Indexed by `finding_index` (1-based). The triangulator references
    findings by index — never by free text — preserving the structural-
    provenance contract across both streams.

    `source_url` / `source_title` / `published_at` come from the grounding
    tool's citation metadata, not from the LLM. The LLM produces only
    `claim` + `specifics` + index assignments.
    """

    finding_index: int = Field(description="1-based index within this report's web_findings list.")
    claim: str = Field(description="One-line factual claim from the web.")
    specifics: str = Field(description="The number, date, name, or quote that anchors the claim.")
    source_url: str = Field(description="From the grounding tool's citation metadata.")
    source_title: str = Field(description="From the grounding tool's citation metadata.")
    published_at: datetime | None = Field(
        default=None, description="From the grounding metadata when available."
    )
    confidence: SignalStrength = Field(description="Service-assigned, not LLM-assigned.")

    @computed_field
    @property
    def id(self) -> str:
        """Stable content-addressed evidence id (``w:<hash of source_url|claim>``)."""
        return _evidence_id("w", self.source_url, self.claim)


# ──────────────────────────────────────────────────────────────────────────
# Corpus-level statistics + exploration report
# ──────────────────────────────────────────────────────────────────────────


class ExplorationReport(BaseModel):
    """What the three-bucket triage actually produced for this run.

    Surfaced in the report's corpus_shape banner. The honest funnel:
    threads_pulled (raw archive) → threads_auto_{accepted,rejected} by
    cosine triage → threads_classified by middle-bucket LLM →
    threads_relevant (passed classifier) → threads_synthesized (post
    embed-group dedup).

    `noise_composition` is binned reason counts from the classifier — what
    KIND of irrelevant content dominated the rejected pile.
    """

    threads_pulled: int
    threads_auto_accepted: int
    threads_auto_rejected: int
    threads_classified: int
    threads_relevant: int
    threads_synthesized: int
    noise_composition: dict[str, int] = Field(default_factory=dict)
    similarity_percentiles: dict[str, float] = Field(default_factory=dict)
    hybrid_percentiles: dict[str, float] = Field(
        default_factory=dict,
        description=(
            "Percentile bands (p10..p90) of the blended cosine + BM25 hybrid "
            "score that actually drives the bucketing. Empty for legacy "
            "reports that ran on cosine-only triage."
        ),
    )


class CorpusStats(BaseModel):
    """Statistical aggregates across the relevant corpus.

    Distinct from ExplorationReport (which is the funnel) — these are
    distributions over the threads that survived triage and were synthesized.
    """

    percentile_bands: dict[str, int] = Field(
        default_factory=dict, description="Decile → thread count."
    )
    subreddit_distribution: list[SourceMapEntry] = Field(default_factory=list[SourceMapEntry])
    time_distribution: dict[str, int] = Field(
        default_factory=dict, description="ISO month → thread count."
    )


# ──────────────────────────────────────────────────────────────────────────
# Cross-stream synthesis output
# ──────────────────────────────────────────────────────────────────────────


class CrossReference(BaseModel):
    """One verified link between a Reddit cluster and the web findings.

    At the LLM-output boundary, the triangulator returns list-id-prefixed
    indices ('cluster:3', 'web:7'). The triangulator validator strips the
    prefix and enforces that cluster ids are valid InsightCluster ranks and
    web ids are valid WebFinding finding_indexes before producing this
    contract. Mixed-list refs are rejected.
    """

    cluster_rank: int = Field(description="1-based rank, references InsightCluster.rank.")
    web_finding_indices: list[int] = Field(
        description="1-based indices, reference WebFinding.finding_index."
    )
    agreement: Literal["agree", "silent_web", "silent_corpus", "disagree"] = Field(
        description="How the streams relate on this claim."
    )
    note: str = Field(
        description="One-line synthesis: where they converge, or what the disagreement is."
    )


# ──────────────────────────────────────────────────────────────────────────
# DemandReport — the canonical output
# ──────────────────────────────────────────────────────────────────────────


class DemandReport(BaseModel):
    """The full report — the canonical shape returned by every surface.

    Optional / default-empty fields keep the additive-contract parity guard
    passing (reports produced by earlier shapes validate against this).
    """

    # ── Core ──
    report_id: str
    client_id: str = Field(
        default="local",
        description="Owning tenant. Set by the service, never the LLM. "
        "Defaults to 'local' for library/CLI use.",
    )
    # ── Lineage (live-view versioning) ──
    # A report is a VIEW over the corpus; a `research refresh` re-synthesizes
    # against the now-larger corpus and pins a NEW version in the same lineage.
    # The materialized artifact stays keyed by `report_id` (unique per version,
    # so `runs/<report_id>/` and portability are unchanged); `lineage_id` is the
    # stable handle that survives refreshes. Additive + defaulted: a v1 run and
    # any pre-lineage report both read as version 1 of their own lineage.
    lineage_id: str = Field(
        default="",
        description="Stable id for this report's refresh lineage. Empty ⇒ first "
        "version (read `effective_lineage_id`, which falls back to `report_id`).",
    )
    version: int = Field(
        default=1, description="Monotonic version within the lineage (1 = original run)."
    )
    parent_report_id: str | None = Field(
        default=None,
        description="The prior version's `report_id` this refresh supersedes. None for v1.",
    )
    query: str
    fork: Fork
    pinned_axis: str
    optimized_axis: str
    source: str = Field(
        default="reddit_arctic_shift",
        description="Provenance of the corpus this run drew on: "
        "'reddit_arctic_shift' | 'reddit_live' | 'hackernews' | 'reviews' | 'mixed'.",
    )
    date_range_start: datetime
    date_range_end: datetime
    total_threads: int
    total_distinct_authors: int
    ranked_clusters: list[InsightCluster]
    partial: bool = False
    caveat: str | None = None
    created_by: str = Field(
        default="library", description="'library' | 'cli' | 'mcp' | 'ui' | 'agent'."
    )
    generated_at: datetime

    # ── Verdict / sizing / pricing (all optional) ──
    verdict: str | None = None
    slot_plan: SlotPlan | None = None
    audience_profile: AudienceProfile | None = None
    segments: list[AudienceSegment] = Field(default_factory=list[AudienceSegment])
    market_sizing: MarketSizing | None = None
    price_finding: PriceFinding | None = None
    source_map: list[SourceMapEntry] = Field(default_factory=list[SourceMapEntry])

    # ── Two-stream additions ──
    brief: ResearchBrief | None = Field(
        default=None,
        description="The brief this run was produced against (frozen-version FK).",
    )
    web_findings: list[WebFinding] = Field(default_factory=list[WebFinding])
    corpus_stats: CorpusStats | None = None
    corpus_shape: ExplorationReport | None = None
    cross_references: list[CrossReference] = Field(default_factory=list[CrossReference])
    must_address_resolution: dict[str, str] = Field(
        default_factory=dict,
        description="must_address item → 'cluster:N' | 'web:N' | 'unaddressable: <reason>'.",
    )

    @property
    def effective_lineage_id(self) -> str:
        """The lineage handle, falling back to ``report_id`` for v1 / pre-lineage
        reports (where ``lineage_id`` is empty). Use this — never raw
        ``lineage_id`` — when grouping versions of the same report."""
        return self.lineage_id or self.report_id

    @property
    def evidence(self) -> list[EvidenceRecord]:
        """Flat, de-duplicated evidence backing this report.

        This is what downstream pillars' ``EvidenceRef``s resolve against
        (by ``EvidenceRecord.id``). Derived on access — never stored or
        serialized, so it is always consistent with the report's own fields
        after a JSON round-trip. De-dups by id (the same quote can back more
        than one cluster).
        """
        records: dict[str, EvidenceRecord] = {}
        for cluster in self.ranked_clusters:
            for q in cluster.quotes:
                records.setdefault(
                    q.id,
                    EvidenceRecord(
                        id=q.id, kind="quote", text=q.text, url=q.source_url, provenance="verbatim"
                    ),
                )
        for w in self.web_findings:
            records.setdefault(
                w.id,
                EvidenceRecord(
                    id=w.id, kind="web", text=w.claim, url=w.source_url, provenance="grounded-web"
                ),
            )
        if self.price_finding is not None:
            for p in self.price_finding.evidence:
                records.setdefault(
                    p.id,
                    EvidenceRecord(
                        id=p.id,
                        kind="price",
                        text=p.text,
                        url=p.permalink or "",
                        provenance="verbatim" if p.permalink else "derived",
                    ),
                )
        return list(records.values())


# ──────────────────────────────────────────────────────────────────────────
# Compact summaries
# ──────────────────────────────────────────────────────────────────────────


class ReportSummary(BaseModel):
    """Compact shape for list endpoints and artifact cards."""

    report_id: str
    query: str
    fork: Fork
    total_threads: int
    total_distinct_authors: int
    generated_at: datetime
    top_claims: list[str] = Field(default_factory=list)
    brief_id: str | None = None

    @classmethod
    def from_report(cls, report: DemandReport, top_n: int = 3) -> ReportSummary:
        return cls(
            report_id=report.report_id,
            query=report.query,
            fork=report.fork,
            total_threads=report.total_threads,
            total_distinct_authors=report.total_distinct_authors,
            generated_at=report.generated_at,
            top_claims=[c.claim for c in report.ranked_clusters[:top_n]],
            brief_id=report.brief.brief_id if report.brief else None,
        )


class RunSummary(BaseModel):
    """Compact shape for run listings — one entry per run, including in-flight."""

    report_id: str
    brief_id: str | None = None
    query: str
    status: Literal[
        "queued",
        "planning_brief",
        "pulling_arctic_shift",
        "embedding_triage",
        "llm_classifying",
        "analyzing_relevant",
        "web_research",
        "compiling",
        "complete",
        "failed",
        "compile_failed",
        "oom_chunked",
    ]
    progress: str | None = None
    error: str | None = None
    total_distinct_authors: int | None = None
    created_at: datetime
    generated_at: datetime | None = None
    ready_at: datetime | None = None
